["!local"]
rockTexture = "minecraft:block/stone"
lateGeneration = true
useGetDrops = false

[":tin_ore"]
oreTexture = "ftbic:block/ore_overlays/tin"

[":uranium_ore"]
oreTexture = "ftbic:block/ore_overlays/uranium"

[":aluminum_ore"]
oreTexture = "ftbic:block/ore_overlays/aluminum"

[":lead_ore"]
oreTexture = "ftbic:block/ore_overlays/lead"

[":iridium_ore"]
oreTexture = "ftbic:block/ore_overlays/iridium"

[":deepslate_tin_ore"]
oreTexture = "ftbic:block/ore_overlays/tin"
rockTexture = "minecraft:block/deepslate"

[":deepslate_uranium_ore"]
oreTexture = "ftbic:block/ore_overlays/uranium"
rockTexture = "minecraft:block/deepslate"

[":deepslate_aluminum_ore"]
oreTexture = "ftbic:block/ore_overlays/aluminum"
rockTexture = "minecraft:block/deepslate"

[":deepslate_lead_ore"]
oreTexture = "ftbic:block/ore_overlays/lead"
rockTexture = "minecraft:block/deepslate"

[":deepslate_iridium_ore"]
oreTexture = "ftbic:block/ore_overlays/iridium"
rockTexture = "minecraft:block/deepslate"