["!local"]
rockTexture = "minecraft:block/stone"
lateGeneration = true
useGetDrops = false

[":ore_aluminum"]
oreTexture = "immersiveengineering:block/metal/ore_aluminum"
maxOreLayerColorDiff = 70
#50

[":ore_uranium"]
oreTexture = "immersiveengineering:block/metal/ore_uranium"

[":ore_lead"]
oreTexture = "immersiveengineering:block/metal/ore_lead"

[":ore_nickel"]
oreTexture = "immersiveengineering:block/metal/ore_nickel"

[":ore_silver"]
oreTexture = "immersiveengineering:block/metal/ore_silver"

[":deepslate_ore_aluminum"]
oreTexture = "immersiveengineering:block/metal/ore_aluminum"
maxOreLayerColorDiff = 70
rockTexture = ":block/deepslate"

[":deepslate_ore_uranium"]
oreTexture = "immersiveengineering:block/metal/ore_uranium"
rockTexture = ":block/deepslate"

[":deepslate_ore_lead"]
oreTexture = "immersiveengineering:block/metal/ore_lead"
rockTexture = ":block/deepslate"

[":deepslate_ore_nickel"]
oreTexture = "immersiveengineering:block/metal/ore_nickel"
rockTexture = ":block/deepslate"

[":deepslate_ore_silver"]
oreTexture = "immersiveengineering:block/metal/ore_silver"
rockTexture = ":block/deepslate"