["!local"]
rockTexture = "minecraft:block/stone"
lateGeneration = true
useGetDrops = false

[":ore_aluminum"]
oreTexture = ":block/metal/ore_aluminum"
maxOreLayerColorDiff = 70
#50

[":ore_uranium"]
oreTexture = ":block/metal/ore_uranium"
maxOreLayerColorDiff = 70

[":ore_lead"]
oreTexture = ":block/metal/ore_lead"
maxOreLayerColorDiff = 70

[":ore_nickel"]
oreTexture = ":block/metal/ore_nickel"
maxOreLayerColorDiff = 70

[":ore_silver"]
oreTexture = ":block/metal/ore_silver"
maxOreLayerColorDiff = 70

[":deepslate_ore_aluminum"]
oreTexture = ":block/metal/deepslate_ore_aluminum"
maxOreLayerColorDiff = 70
rockTexture = "minecraft:block/deepslate"

[":deepslate_ore_uranium"]
oreTexture = ":block/metal/deepslate_ore_uranium"
maxOreLayerColorDiff = 70
rockTexture = "minecraft:block/deepslate"

[":deepslate_ore_lead"]
oreTexture = ":block/metal/deepslate_ore_lead"
maxOreLayerColorDiff = 70
rockTexture = "minecraft:block/deepslate"

[":deepslate_ore_nickel"]
oreTexture = ":block/metal/deepslate_ore_nickel"
maxOreLayerColorDiff = 70
rockTexture = "minecraft:block/deepslate"

[":deepslate_ore_silver"]
oreTexture = ":block/metal/deepslate_ore_silver"
maxOreLayerColorDiff = 70
rockTexture = "minecraft:block/deepslate"