["!local"]
rockTexture = ":block/stone"

[":inferium_ore"]
oreTexture = ":block/inferium_ore"

[":deepslate_inferium_ore"]
oreTexture = ":block/inferium_ore"
rockTexture = "minecraft:block/deepslate"

[":prosperity_ore"]
oreTexture = ":block/prosperity_ore"

[":deepslate_prosperity_ore"]
oreTexture = ":block/prosperity_ore"
rockTexture = "minecraft:block/netherrack"

[":soulium_ore"]
oreTexture = ":block/soulium_ore"
rockTexture = ":block/soulstone"